### ISSUE TITLE
0.3 release?

### ISSUE THREAD

**Issue by archon810** [ryanbagwell/wordpress-sentry#13]
Hi, 

https://wordpress.org/plugins/getsentry-client/ mentions v0.3 but this github only has 0.1 and 0.2. What's the latest stable release and if it's 0.3, could you tag the right one here in github?

**Comment by archon810** [comment]
Additionally, after being installed, github master just says "Version 1 | By Ryan Bagwell | View details" on the Plugins page in WP.

**Comment by archon810** [comment]
So this github, which I thought was what the svn was pulling from, is not actually the main repo but the other way around. In this case, I guess, I'm going to add the wpackagist version that mirrors svn into our site instead of this repo directly. Or are you going to catch it up and keep it updated?

http://wpackagist.org/search?q=getsentry-client&type=any&search=

**Comment by ryanbagwell** [comment]
@archon810 I think I just fixed everything after bumping versions up to 1.0. It seems to be correct on the wp plugins page. Let me know if there's something else I need to do.
